### ISSUE TITLE
Getting "Not found" when embedding video

### ISSUE THREAD

**Issue by philgyford** [jdsdev/Embedder#10]
I'm doing this:

```
{ {{ craft.embedder.embed ('https://www.youtube.com/watch?v=ougF5Q78tyo', {max_width:500, max_height:800}) }}
```

but it only outputs "Video not found".

I can embed the video in a template manually using this:

```
 <iframe width="560" height="315" src="https://www.youtube.com/embed/ougF5Q78tyo" frameborder="0" allowfullscreen></iframe> 
```

so I guess it's not a permissions/rights issue about embedding.

**Comment by A-P** [comment]
Looks like your syntax is just slightly off - I think you have an extra `{` at the beginning of your line. This code worked fine for me: 

``` twig
    {{ craft.embedder.embed ('https://www.youtube.com/watch?v=ougF5Q78tyo', {max_width:500, max_height:800}) }}
```

**Comment by philgyford** [comment]
Oops, sorry for wasting your time. It seems odd that Craft/Twig didn't complain about the syntax, but I should have noticed that. Thanks.

**Comment by A-P** [comment]
No problem at all - I've done the same thing many times :+1:
