### ISSUE TITLE
vimeo parameters

### ISSUE THREAD

**Issue by matanlevkowich** [jdsdev/Embedder#11]
Hello there,

Great plugin, very nice. I have an amatur question, I am trying to add vimeo parameters but with no success. Where exactly in the code I should add it?

I have tried to do it like that with no success:

{% set video = craft.embedder.url(entry.workVideo, {max_width:5000, max_height:8000, vimeo_color:ffffff}) %}
    <div class="work_video">
        {{ video.embed_code }}  
    </div>

Any advice on what I am doing wrong?
Thanks!

**Comment by lindseydiloreto** [comment]
For reference, this question was also posed on Stack Exchange...

> http://craftcms.stackexchange.com/questions/10225/embedder-plugin-issue

When a solution has been determined, please post the answer over there as well. Thanks!

**Comment by lindseydiloreto** [comment]
I haven't personally used this plugin, but I'd recommend putting that string **in quotes**...

```
vimeo_color:"ffffff"
```

**Comment by A-P** [comment]
@lindseydiloreto is correct - you have to put the color in a string. This code should work fine:

``` twig
{% set video = craft.embedder.url(entry.workVideo, {max_width:5000, max_height:8000, vimeo_color:"ffffff"}) %}

{{ video.embed_code }}
```

One other thing to note - with Vimeo, a video owner can overwrite this option - so if they set it to a specific theme color, you can't change it through this embed parameter.
