### ISSUE TITLE
Curl failing silently

### ISSUE THREAD

**Issue by philgyford** [jdsdev/Embedder#13]
I just had an issue where embedding a Vimeo video kept displaying 'Video not found' on one server, but it worked on another. It turned out the failing server [needed root certificates setting](https://raw.github.com/bagder/curl/master/lib/mk-ca-bundle.vbs) for curl to work.

I only worked this out by going through the code and realising curl was failing silently. Would it be worth adding [this kind of exception handling](http://stackoverflow.com/a/13311209/250962) in `EmbedderService::curl()` so that such errors are more visible and solvable?

**Comment by jdsdev** [comment]
I've just taken over Embedder to update it for Craft 3. I'm closing old issues so we can have a fresh start, but let me know if you want to revisit the issue and we can reopen it. Thanks!
