### ISSUE TITLE
Using a fallback if YouTube thumbnail doesn't exist

### ISSUE THREAD

**Issue by katrinkerber** [jdsdev/Embedder#18]
I am using the Embedder to pull in thumbnails for videos and then Imager to transform them.

I've been having issues with thumbnails that don't exist, which you can see in the [issue thread].(https://github.com/A-P/Embedder/issues/new)

Whilst this has been resolved, I now get the grey placeholder image that Youtube falls back on when the thumbnail for the video doesn't exist.

Is there a way to detect if a video thumbnail actually exists so that I could use a custom fallback in case it doesn't?

**Comment by mikestecker** [comment]
I just ran into the same issue. This is my code:

```
{% set vid = craft.embedder.url(block.videoUrl, {max_width:1920, max_height:1280, youtube_rel:0, youtube_showinfo:0, vimeo_byline:false, vimeo_title:false, vimeo_portrait:false, vimeo_color:"F36B25"}) %}

{% if vid.video_highres %}
  {% set thumb = vid.video_highres|t %}
{% elseif vid.video_mediumres %}
  {% set thumb = vid.video_mediumres|t %}
{% else %}
  {% set thumb = vid.video_thumbnail|t %}
{% endif %}
```

What I end up getting is what is considered `highres` (`maxresdefault.jpg` according to their API) but ends up being a tiny, grey ugly thumbnail. I wonder if you could put width/height contingencies on what is being returned?

Here is the direct link to the thumbnail on Youtube:
http://img.youtube.com/vi/v4OdoaZNkN4/maxresdefault.jpg
http://img.youtube.com/vi/v4OdoaZNkN4/hqdefault.jpg
http://img.youtube.com/vi/v4OdoaZNkN4/mqdefault.jpg

**Comment by katrinkerber** [comment]
Detecting the width/height of the returned thumbnail was also a train of thought I had :) 

In the end I went with checking the file size, as I discovered that the grey fallback thumbnail was tiny in size compared to 'real' thumbnails.

Here’s the code I ended up with:

```
{# using both the Embedder and Imager plugin to create thumbnail #}
{% set videoEmbedderUrl = item.videoUrl|replace({'youtube.com/embed/': 'youtube.com/watch?v='}) %}
{% set videoEmbedderElement = craft.embedder.url(videoEmbedderUrl) %}
{% set videoThumb = videoEmbedderElement.video_highres|replace('https', 'http') %}

{% set videoThumbCroppedUrl = '' %}
{% set videoThumbCropped = craft.imager.transformImage(videoThumb, [{ width: 640, height: 428 }]) %}
{% for videoThumbCropped in videoThumbCropped %}
  {% if videoThumbCropped.getSize('k') < 10 %}
    {% set videoThumbCroppedUrl = '/assets/images/placeholder.png' %}
  {% else %}
    {% set videoThumbCroppedUrl = videoThumbCropped.getUrl() %}
  {% endif %}
{% endfor %}

<img src="{{ videoThumbCroppedUrl }}" alt="Thumbnail of {{ item.title }}">
```

You could probably adjust the code to grab a different size thumbnail if the first attempt resulted in the grey fallback thumbnail rather than using a placeholder image :)

**Comment by jdsdev** [comment]
I've just taken over Embedder to update it for Craft 3. I'm closing old issues so we can have a fresh start. Fallbacks do sound like they could be useful, though I personally haven't had need for them yet. We can reopen the issue if you want to revisit it for Craft 3. Just let me know (and maybe add some fresh links to dead thumbnails if you get the chance). Thanks!
