### ISSUE TITLE
how to pull embedder field in matrix

### ISSUE THREAD

**Issue by rdhrkns** [jdsdev/Embedder#20]
As I'm completely new to this it might be a beginner question, but I'm struggeling to pull the data from an embedder field in a matrix block field using the switch statement.

Using the example codes on this repository throws me all kind of errors. Some simple example to start from would be appreciated to get me going again.

**Comment by jdsdev** [comment]
I've just taken over Embedder to update it for Craft 3. I'm closing old issues so we can have a fresh start, but let me know if you want to revisit the issue and we can reopen it. Thanks!
