### ISSUE TITLE
Fieldtype doesn't do anything?

### ISSUE THREAD

**Issue by timkelty** [jdsdev/Embedder#25]
Theres a fieldtype included...but it doesn't do anything (it's just a text field).

Seems like you'd want to do something like:

```
	public function prepValue($value)
	{
		return craft()->embedder->embed($value, array(), false);
	}
```

so it was actually useful!

**Comment by jdsdev** [comment]
I've just taken over Embedder to update it for Craft 3. I'm closing old issues so we can have a fresh start, but let me know if you want to revisit the issue and I can have a look into it. (Honestly I wondered the same thing myself at one point, but the text field always did the trick for me.)
