### ISSUE TITLE
Videos don't scale anymore.

### ISSUE THREAD

**Issue by ghost** [jdsdev/Embedder#26]
For some reason the embedded videos don't scale anymore. Here's a example:
http://hildeelbers.nl/theater/the-animated

**Comment by jdsdev** [comment]
I've just taken over Embedder to update it for Craft 3. I'm closing old issues so we can have a fresh start, but let me know if you want to revisit the issue and we can reopen it. It would help to have some more details if you're still having the issue though. Thanks!
