### ISSUE TITLE
Ability to extract the src url from {{ video.embed_code }}

### ISSUE THREAD

**Issue by sethburtonhall** [jdsdev/Embedder#28]
I have a need to get the src url from the iframe when embedding via `{{ video.embed_code }}`

Ideally `{{ video.embed_code_url }}` or `{{ video.embed_src }}` or the like.

**Comment by jdsdev** [comment]
I've just taken over Embedder to update it for Craft 3. I'm closing old issues so we can have a fresh start, but let me know if you want to revisit the issue and I can have a look into it. Thanks!
