### ISSUE TITLE
Vimeo Thumbnails not showing

### ISSUE THREAD

**Issue by mikednz** [jdsdev/Embedder#32]
For some reason Vimeo thumbnails are no longer showing?
{% for video in blocks %}

	{% set vimeo = craft.embedder.url(video.vimeoUrl, {max_width:500, max_height:800}) %}
		
{{ vimeo.video_highres }}

	{% endfor %}

**Comment by jdsdev** [comment]
I just checked, and Vimeo thumbnails still seem to be working for me. Could you let me know if the problem has resolved for you? Occasionally a thumbnail will be missing from one of the source sites.

I just updated the code for Craft 3, but that was after your issue. The Craft 2 code hasn't change for quite a while, so nothing should be different. You can find it in [the v1 branch](https://github.com/jdsdev/Embedder/tree/v1) if needed.

**Comment by jdsdev** [comment]
Closing this issue as inactive, but you can let me know if you run into the problem again.
