### ISSUE TITLE
Youtube embeds not showing up

### ISSUE THREAD

**Issue by architchandra** [jdsdev/Embedder#33]
Plugin version: 2.0.0
Craft version: 3.4.30

This was only noticed today. Could it also be related to the Google outage that happened recently? The embed is showing up if I directly paste the embed code in a template, though.

**Comment by jdsdev** [comment]
I hadn't noticed the issue until you pointed it out either, the update I just pushed should fix the issue. It looks like the YouTube API was updated when the outage happened yesterday.

**Comment by architchandra** [comment]
Thank you so much. Will update.
