### ISSUE TITLE
Youtube video set to private causes 404?

### ISSUE THREAD

**Issue by sonoflee** [jdsdev/Embedder#35]
On a Craft site I work with, there are a series of event entries that each have a YouTube link, which are then rendered to their entry pages using the Embedder plugin.  When a video is set to private on YouTube, the page returns a 404.  If I delete that YouTube link altogether (or input one that is verified to be set to public), the page loads fine.

Questions:
- Is this the expected behavior?
- If so, I'm wondering if there's a way to "fail silently" on these instead?

Thanks for any info!

**Comment by jdsdev** [comment]
It looks like there was an issue with the code that's supposed to handle graceful failure when a video isn't found. I've just updated it, and it should now show "Video not found" if you are using the simple embed code `craft.embedder.embed`. I'm surprised that nobody has noticed this behavior before.
