### ISSUE TITLE
Feature request: add option to use youtube's no-cookie embed

### ISSUE THREAD

**Issue by sonoflee** [jdsdev/Embedder#36]
YouTube hasn't added an option to their API to return oembed requests in their [privacy enchanced mode](https://support.google.com/youtube/answer/171780?hl=en#zippy=%2Cturn-on-privacy-enhanced-mode).  

In Embedder, would it be possible to add an additional YT config option (maybe `youtube_dnt=1`) that would, in effect, replace the 
string `youtube.com/embed` in the returned embed with `youtube-nocookie.com/embed`?  Thank you for considering.

**Comment by jdsdev** [comment]
Rather than adding non-standard parameters, I could add detection for `youtube-nocookie.com` urls and use those to generate the embed code. Would that work for your use case?

**Comment by sonoflee** [comment]
Thank you for the quick response! 

I can see value in either approach:  a parameter makes more sense for implementing site-wide changes for more GDPR-friendly embeds, while using the no-cookie URL would allow a per-entry changes to the embeds.  

For my use case, the parameter method would be preferable: it would allow me to reflect sitewide privacy policies across the site more easily and make enforcing those policy changes simpler for multiple authors/editors.  I think that most who'd want to use privacy enhanced embeds would probably have a similar use case.

For reference, [Hugo](https://gohugo.io/about/hugo-and-gdpr/#youtube) adopts a parameter-like option, and it looks like there are some interesting takes in both directions on this [Wordpress core ticket](https://core.trac.wordpress.org/ticket/44610).

**Comment by jdsdev** [comment]
After looking into it more I've added the `youtube_privacyEnhanced` parameter, soon to be released. Google seems to have made a point of making it roundabout to use the youtube-nocookie.com domain.
