### ISSUE TITLE
Add element 'class' option 

### ISSUE THREAD

**Issue by m9dfukc** [jdsdev/Embedder#7]
Would be nice that have an addition 'class' option so we could use it with [bootstrap's responsive embed](http://getbootstrap.com/components/#responsive-embed).

**Comment by jacobgraf** [comment]
Agree! Anyway to 'hack' this in the meantime to support that?

**Comment by sethburtonhall** [comment]
agreed. adding an id or class to `{{ video.embed_code }}` would be very helpful.
