### ISSUE TITLE
New version has removed video_code property?

### ISSUE THREAD

**Issue by markstewie** [jdsdev/Embedder#9]
Hi there, Embedder is awesome but I've just updated a client site using it and found you've removed the video_code property which breaks the site? I need this for some custom functionality for the youtube videos being loaded. Is this property still available anywhere?

**Comment by A-P** [comment]
Hi @markstewie - I don't think we've ever used a video_code property, but we do have embed_code - is that what you're looking for?

**Comment by markstewie** [comment]
Hey @A-P now you say that, I think I actually might have made a custom modification to the plugin originally to add this but forgot that I did this. Sorry!
